language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: heroku
  api_key:
    secure: iNiXpaXsrXpK+famtjS3RSmN4WGp1M+4NdVC5WAwibwOQXLuAfvotJNZ7s6R8Q1lq7gGQmaNAKYy/+rNeCYpzBH1NO5F3IwwccofYe3Jj/Fb7NpFZnbA5OCzAJ3Xw1rPhRoo4UIBkOkMh1HL0OsK9iVUZQfFNs9blEFjU2p+nuCijb9WOLTgQ4354GKyQvGen130LJR7gjPl1oZVNaLOe75CuBeQ/CF5RQGMRlaOyt8rypg1DdIxdE5bzt5sdCNe6u6L/KWjFllk4Qm7tuEb/xqZf41pCjthc8XpNUw7wrFy7qH7bCbfFzpQkGFPMKKnd3R6HVJ1ddYM+SWE6ofIuGaZXTD29dry0Cajm324jYje5ZtIIdPp3C6VoVS7TOBfAKa/LkiXh0P86MTQL2GPuuHLEENpnqyV/w0vpJQQgteHNn2fRF5I5oHJxDVBbdxsd51liUlcgWghkLDRuF1yAioj5LD1ZoOBQlpXi9nh/LvPda8w6en7cAkUhPa2xngjQHGoa1XxpiFSJtuPoavs2N7DxS0u6hc0dcYaHSs9VaYCc5qrO8QgE3fHlleilFOD7PqZsVkf0Jxsddyqql6uFkJdrzrGiDlCCvY6X0ZIHxO2x/fg4oqjNdx07wjbJWbhNmr3BLVIi2zTBFJoyl5vWMluG7MofaEiwjIOppbAjZU=
  app: condensate-app
  skip_cleanup: true
